### ISSUE TITLE
Where is all the code?

### ISSUE THREAD

**Issue by xrisk** [milankragujevic/BrowserPopcorn#4]
… This is just the webpage :/

**Comment by ricardobarantini** [comment]
Yeah, technacally the "website" made it all work.

**Comment by xrisk** [comment]
@ricardobarantini  What about  all the server side code ?

**Comment by ClayF** [comment]
Yeah, I'd like to check it out. I'm interested.

**Comment by malonehedges** [comment]
@milankragujevic What are your thoughts on open sourcing the server side code?

**Comment by matthewbauer** [comment]
Based on user history it looks like it's probably using peerflix to stream torrents. Probably also using some version of the YTS api through https://browserpopcorn.xyz/api/.

I can't believe this is all being done on the server-side. Regardless of copyright issues, a single server trying to host torrent traffic on a public website is not going to stay up long.

It would be nice if this could be clearly differentiated from the original Popcorn Time because it shares no source code. I think some Popcorn Time devs were looking into a proper client side browser port but I don't think it went anywhere.

**Comment by liltimtim** [comment]
if anyone is interested... API access is at:

https://api.browserpopcorn.xyz/movies/comedy?key=33df481a67a61485d34e36e847895cd008439d72

I'm guessing the code he wrote here doesn't exactly mimic what is running the website. But at least you can see what JSON it's spitting out.

**Comment by Danappelxx** [comment]
@liltimtim Unfortunately that url doesn't work because the key expired

**Comment by liltimtim** [comment]
Just open chrome go to chrome://net-internals.  You can see the URL requests it's generating.  I'm also betting you can find the API endpoint that does the token request and exchange. I haven't put much effort into it.

**Comment by liltimtim** [comment]
Further looking at his source code, he is pulling /assets/app.js?v=4.0 from his server.  I looked at the window.api_key set inside the HTML file itself. <script>window.api_key='33df481a67a61485d34e36e847895cd008439d72'</script>

so it is possible that the server is assigning a token and is inserting into the HTML before it is served to the browser.

**Comment by liltimtim** [comment]
Also, if you read his copyright, this isn't open source technically.  He doesn't place this code under Apache license or the MIT license.  Just an FYI.

**Comment by milankragujevic** [comment]
The PHP and Node.js code that runs the website is proprietary. The only thing publicly available is the web site UI. My git doesn't work currently. I'll try to get it working and commit the newest changes.
